@startmindmap 
*[#Orange] Javascript 
**[#Lime] Variables 
***[#DarkCyan] Keywords  
****[#Coral] let 
****[#Coral] const 
****[#Coral] var 
***[#DarkCyan] Tipos de Datos  
****[#Coral] Textos
****[#Coral] Números 
****[#Coral] Booleanos  
****[#Coral] Contenedores  
*****[#DarkViolet] Arrays
****[#Coral] Fechas  
***[#DarkCyan] Alcance   
**[#Lime] Condicionales 
***[#DarkCyan] if else  
***[#DarkCyan] switch        
**[#Lime] Bucles (Loops)
***[#DarkCyan] while 
***[#DarkCyan] for       
**[#Lime] Funciones  
***[#DarkCyan] Anónimas 
***[#DarkCyan] Con nombre
****[#Coral] Métodos
*****[#DarkViolet] Parámetros 
****[#Coral] Atributos 
**[#Lime] Exceptions  
**[#Lime] Comentarios 
@endmindmap 